namespace: kube-system

resources:
  - rbac.yaml
  - init-job.yaml
  - service.yaml
  - sts.yaml

vars:
  - name: MINIO_NAMESPACE
    objref:
      kind: Service
      name: minio
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: MINIO_SERVICE_NAME
    objref:
      kind: Service
      name: minio
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: MINIO_STS_NAME
    objref:
      kind: StatefulSet
      name: minio
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.name
  - name: MINIO_SETUP_JOB_NAME
    objref:
      kind: Job
      name: minio-setup
      apiVersion: batch/v1
    fieldref:
      fieldpath: metadata.name

images:
  - name: minio/minio
    newTag: RELEASE.2020-09-17T04-49-20Z
  - name: minio/mc
    newTag: RELEASE.2020-09-03T00-08-28Z

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: minio-credentials
  envs: 
    - cloud-credentials.env
- name: cloud-credentials
  files:
    - cloud=cloud-credentials.config