# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../velero-base

commonLabels:
  module.kfd.sighup.io/name: "dr"
  module.kfd.sighup.io/version: "v1.8.0"
  module.kfd.sighup.io/component: "velero-gcp"
  kfd.sighup.io/source: "kustomize"

images:
  - name: velero/velero-plugin-for-gcp
    newName: registry.sighup.io/fury/velero/velero-plugin-for-gcp
    newTag: v1.3.0
  - name: velero/velero-plugin-for-csi
    newName: registry.sighup.io/fury/velero/velero-plugin-for-csi
    newTag: v0.2.0

patchesStrategicMerge:
  - plugin-patch.yaml
